### ISSUE TITLE
Responsive ?

### ISSUE THREAD

**Issue by bckthomas** [Tanner3644/home-assistant-config#1]
Hi @Tanner3644 
I love your work !
Do you plan to make it responsive ?

**Comment by Tanner3644** [comment]
Hi @bckthomas There are no plans to make it responsive. Your best bet would be to familiarize your self with the custom lay out card or increase/decrease the button sizes to fill or take up less of the screen.

**Comment by bckthomas** [comment]
I will learn how to use the custom layout card
Thanks !
